# Configuration Dapr avec Zipkin
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: dapr-config
spec:
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: "http://zipkin:9411/api/v2/spans"
---
# State Store Redis
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: state-redis
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: redis:6379
  - name: redisPassword
    value: ""
  - name: actorStateStore
    value: "true"
---
# PubSub Redis
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub-redis
spec:
  type: pubsub.redis
  version: v1
  metadata:
  - name: redisHost
    value: redis:6379
  - name: redisPassword
    value: ""
scopes:
  - checkout-service
  - order-service
---
# Cron Binding
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: binding-cron
spec:
  type: bindings.cron
  version: v1
  metadata:
  - name: schedule
    value: "*/5 * * * * *"