apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "product-service"
        dapr.io/app-port: "8081"
        dapr.io/config: "dapr-config"
    spec:
      containers:
      - name: product-service
        image: product-service:1.0.0
        imagePullPolicy: Never
        ports:
        - containerPort: 8081
      
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  selector:
    app: product-service
  ports:
  - port: 8081
    targetPort: 8081
  type: LoadBalancer